"""manifest_selections

Revision ID: 0001
Revises: 0002
Create Date: 2025-05-11 15:37:33.959274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manifest_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selector_id', sa.String(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['simplestream_product_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manifest_selection_selector_id'), 'manifest_selection', ['selector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manifest_selection_selector_id'), table_name='manifest_selection')
    op.drop_table('manifest_selection')
    # ### end Alembic commands ###
